ford_fulkerson: edge.cpp queueElement.cpp flowGraph.cpp ford_fulkerson.cpp
	g++ -Wall -Wextra -Werror -g -o ford_fulkerson edge.cpp queueElement.cpp flowGraph.cpp ford_fulkerson.cpp -std=c++17 -lstdc++fs -lstdc++ -O3 -I.
